name: Abiel Neagoe CI

on:
    push:
        branches:
        - "**"

jobs:
    build-dtb:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Install dependinces
            run: |
                sudo apt update
                sudo apt install make bc u-boot-tools flex bison libssl-dev tar kmod xz-utils gcc-arm-linux-gnueabi -y

          - name: List available DTS files
            run: |
              ls arch/arm/boot/dts | grep zynq || echo "No zynq DTS files found."



          - name: Build.dtb
            run: |
                export ARCH=arm
                export CROSS_COMPILE=arm-linux-gnueabi-
                make zynq_xcomm_adv7511_defconfig
                make -j6 zynq-coraz7s.dtb

          - name: Upload dtb
            uses: actions/upload-artifact@v4
            with:
                name: dtb
                path: arch/arm/boot/dts/zynq-cora-z7.dtb
